### ISSUE TITLE
blog crawler

### ISSUE THREAD

**Issue by wivina** [xotrs/naver-blog-crawler#1]
안녕하세요,
블로그 크롤러 사용을 위해 입문한 파이썬 초보자입니다. 
업로드하신 크롤러가 굉장히 잘 사용되는데요, 혹시 엑셀로 저장을 하려면 어떻게 수정해야하는지 아시나요?
전 pandas로 dataframe을 만들어 저장하는 방식밖에 몰라서요.
혹시 도움을 주실 수 있을까요?
감사합니다.

**Comment by xotrs** [comment]
안녕하세요? 제가 만든 네이버 블로그 크롤러가 도움이 된다니 다행입니다 :D 
크롤링 한 데이터를 엑셀로 저장하고 싶다면 다음과 같이 진행하면 됩니다.

1. xotrs/naver-blog-crawler 레퍼지토리를 fork
2. 프로젝트 내에서 엑셀 관련 라이브러리를 import
3. 데이터를 넣고 저장하는 코딩 진행

위의 프로세스로 진행하다가 궁금한 점이 있으면 언제든지 질문 남겨주세요.
감사합니다!
