### ISSUE TITLE
문의드립니다.

### ISSUE THREAD

**Issue by hihiee** [xotrs/naver-blog-crawler#2]
안녕하세요! 공유해주신 네이버api 를 사용한 블로그 포스팅 크롤러에 대해 문의드릴 것이 있어 글 남깁니다.
아직 미숙한 학생 입장이라, 적어주신 코드를 그대로 받아 적어 실행시켜 보았는데 포스팅 개수를 가지고 오는 함수는 잘 구현이 되나, 포스팅을 가져오는 밑의 함수의 출력값이 안 떠서요. print 함수에 대한 문제인 것 같은데, 해결방법이 있을까 하여 문의 드립니다. 답변 부탁드리겠습니다. 감사합니다.

**Comment by xotrs** [comment]
안녕하세요! 얼마 전 확인 결과, 네이버 블로그의 구조가 변경되어 포스팅 내용을 제대로 파싱하지 못하는 이슈를 확인했습니다. 조만간 코드를 업데이트 하도록 하겠습니다. 감사합니다.
